import React, { useState } from 'react';
import { Cpu, TrendingUp, TrendingDown, Clock, ShieldCheck, CheckCircle2, BarChart3, ChevronDown, ChevronUp, AlertTriangle } from 'lucide-react';
import { MLData } from '../types';
import { InfoTooltip } from './InfoTooltip';

interface MLPredictionCardProps {
  ml: MLData | null;
  ticker: string;
  isSimpleView?: boolean;
}

export const MLPredictionCard: React.FC<MLPredictionCardProps> = ({ ml, ticker, isSimpleView = true }) => {
  const [showTechnicalDetails, setShowTechnicalDetails] = useState(false);

  if (!ml || ml.status === 'ML DATA UNAVAILABLE' || ml.up_probability === null) {
    return (
      <div className="bg-white border border-gray-200 rounded-2xl p-6 text-center shadow-sm">
        <div className="inline-flex items-center gap-2 px-3 py-1 bg-amber-50 border border-amber-200 text-amber-800 font-mono text-sm rounded-lg mb-2">
          COMPUTER MODEL DATA PENDING
        </div>
        <p className="text-slate-600 text-sm">
          {ml?.error_reason || 'Insufficient past market sessions to compute computer prediction model.'}
        </p>
      </div>
    );
  }

  const isPredictedUp = ml.predicted_next_direction === 'UP';
  const isWeakModel = typeof ml.accuracy === 'number' && ml.accuracy < 55;

  return (
    <div className="bg-white border border-gray-200 rounded-2xl p-6 shadow-sm space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-gray-200 pb-4">
        <div>
          <div className="flex items-center gap-2 text-teal-700 text-xs font-bold uppercase tracking-wider mb-1">
            <Cpu className="w-4 h-4" />
            <span>Computer Model</span>
            <InfoTooltip text="Calculates the probability of an UP or DOWN move for the next session based on historical statistical patterns." />
          </div>
          <h3 className="text-xl font-bold text-gray-900">
            Expected Next Move
          </h3>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500 font-mono">Model:</span>
          <span className="px-3 py-1 bg-gray-100 text-teal-700 border border-gray-200 rounded-xl text-xs font-mono font-bold">
            Computer Model
          </span>
        </div>
      </div>

      {/* Main Direction Banner */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6 bg-gray-50 p-5 rounded-2xl border border-gray-200 items-center">
        {/* Next Session Direction Badge */}
        <div className="md:col-span-5 flex flex-col items-center justify-center p-4 border-b md:border-b-0 md:border-r border-gray-200">
          <div className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 flex items-center gap-1">
            <span>Expected Direction</span>
            <InfoTooltip text="Estimate generated by statistical computer model trained on historical data. Does not guarantee future performance." />
          </div>
          <div
            className={`flex items-center gap-2 px-5 py-2.5 rounded-2xl font-bold text-2xl border shadow-sm ${
              isPredictedUp
                ? 'bg-emerald-50 text-emerald-700 border-emerald-300'
                : 'bg-red-50 text-red-700 border-red-300'
            }`}
          >
            {isPredictedUp ? <TrendingUp className="w-7 h-7 text-emerald-600" /> : <TrendingDown className="w-7 h-7 text-red-600" />}
            <span>{ml.predicted_next_direction}</span>
          </div>

          {isWeakModel && (
            <div className="mt-2.5 px-3 py-1 bg-amber-50 border border-amber-300 text-amber-800 rounded-lg text-[10px] font-sans font-bold text-center">
              Computer Model: Not included in overall score (recent test performance was too weak)
            </div>
          )}

          <div className="text-xs text-slate-500 mt-2">
            Target: Next Trading Session
          </div>
        </div>

        {/* Probabilities Breakdown */}
        <div className="md:col-span-7 space-y-4">
          <div className="text-xs font-bold text-slate-500 uppercase tracking-wider">
            Expected Probability
          </div>

          <div className="space-y-3 font-mono">
            {/* UP Probability */}
            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="text-emerald-700 font-bold flex items-center gap-1">
                  <TrendingUp className="w-3.5 h-3.5" /> Chance of UP move:
                </span>
                <span className="font-bold text-emerald-700">{ml.up_probability}%</span>
              </div>
              <div className="w-full h-2.5 bg-gray-200 rounded-full overflow-hidden border border-gray-200">
                <div
                  style={{ width: `${ml.up_probability}%` }}
                  className="bg-emerald-600 h-full transition-all"
                ></div>
              </div>
            </div>

            {/* DOWN Probability */}
            <div>
              <div className="flex justify-between text-xs mb-1">
                <span className="text-red-700 font-bold flex items-center gap-1">
                  <TrendingDown className="w-3.5 h-3.5" /> Chance of DOWN move:
                </span>
                <span className="font-bold text-red-700">{ml.down_probability}%</span>
              </div>
              <div className="w-full h-2.5 bg-gray-200 rounded-full overflow-hidden border border-gray-200">
                <div
                  style={{ width: `${ml.down_probability}%` }}
                  className="bg-red-600 h-full transition-all"
                ></div>
              </div>
            </div>
            <p className="text-[11px] text-slate-500 font-sans pt-1">
              Note: This probability is calculated from mathematical price indicators and volume history, not guaranteed predictions.
            </p>
          </div>
        </div>
      </div>

      {/* Collapsible Technical Details Trigger */}
      <div className="border-t border-gray-200 pt-3">
        <button
          onClick={() => setShowTechnicalDetails(!showTechnicalDetails)}
          className="w-full flex items-center justify-between p-3 bg-gray-50 hover:bg-gray-100 rounded-xl border border-gray-200 text-xs font-mono text-slate-700 transition-all cursor-pointer"
        >
          <span className="flex items-center gap-2 font-bold text-teal-700">
            <span>{showTechnicalDetails ? 'Technical Details ▲' : 'Technical Details ▼'}</span>
            <span className="text-slate-500 font-normal text-[11px]">(Accuracy, Precision, Recall, F1 Score & Feature Data)</span>
          </span>
          {showTechnicalDetails ? <ChevronUp className="w-4 h-4 text-teal-700" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
        </button>

        {showTechnicalDetails && (
          <div className="mt-3 space-y-4 animate-fadeIn">
            {/* Model Performance Metrics */}
            <div className="space-y-3">
              <div className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center justify-between">
                <span>Model Verification on Unseen Historical Data</span>
                <span className="font-mono text-[11px] text-teal-700">Test Days: {ml.test_sample_count}</span>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono">
                <div className="bg-gray-50 p-3.5 rounded-xl border border-gray-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Prediction Accuracy</div>
                  <div className="text-xl font-bold text-teal-700 mt-1">
                    {ml.accuracy !== null ? `${ml.accuracy}%` : 'N/A'}
                  </div>
                </div>

                <div className="bg-gray-50 p-3.5 rounded-xl border border-gray-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Precision (UP Moves)</div>
                  <div className="text-xl font-bold text-gray-800 mt-1">
                    {ml.precision !== null ? `${ml.precision}%` : 'N/A'}
                  </div>
                </div>

                <div className="bg-gray-50 p-3.5 rounded-xl border border-gray-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">Recall (Hit Rate)</div>
                  <div className="text-xl font-bold text-gray-800 mt-1">
                    {ml.recall !== null ? `${ml.recall}%` : 'N/A'}
                  </div>
                </div>

                <div className="bg-gray-50 p-3.5 rounded-xl border border-gray-200">
                  <div className="text-[10px] font-bold text-slate-500 uppercase">F1 Score Quality</div>
                  <div className="text-xl font-bold text-gray-800 mt-1">
                    {ml.f1_score !== null ? `${ml.f1_score}%` : 'N/A'}
                  </div>
                </div>
              </div>
            </div>

            {/* Validation & Training Info */}
            <div className="bg-gray-50 p-4 rounded-xl border border-gray-200 space-y-2 text-xs font-mono text-slate-600">
              <div className="flex items-center gap-1.5 text-gray-900 font-bold">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>Strict Chronological Train / Test Split</span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-[11px] pt-1">
                <div>
                  <span className="text-slate-400">Training Period:</span>{' '}
                  <span className="text-gray-800">{ml.training_period}</span>
                </div>
                <div>
                  <span className="text-slate-400">Testing Period:</span>{' '}
                  <span className="text-gray-800">{ml.testing_period}</span>
                </div>
              </div>
              <div className="pt-2 text-[10px] text-slate-400 border-t border-gray-200">
                Features: Daily Price Returns, SMA20, SMA50, RSI(14), MACD, and Price Volatility.
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
